uint8 LUNAR_SURFACE=1
uint8 LAVA_TUBE=2
uint8 environment_mode
string request_id
string mission_id
uint64 mission_revision
lunar_planning_msgs/GoalRegion goal
bool replace_active_request
---
uint8 NEW_REFERENCE_AVAILABLE=0
uint8 SAFE_FRONTIER_REFERENCE_AVAILABLE=1
uint8 NO_KNOWN_SAFE_ROUTE=2
uint8 GOAL_INFEASIBLE=3
uint8 INVALID_REQUEST=4
uint8 STALE_INPUT=5
uint8 NUMERICAL_FAILURE=6
uint8 RESOURCE_EXHAUSTED=7
uint8 ACTIVE_REFERENCE_INVALIDATED=8
uint8 CANCELED=9
uint8 ACTIVATE_NEW_REFERENCE=0
uint8 CONTINUE_ACTIVE_REFERENCE=1
uint8 HOLD_POSITION=2
uint8 CONTINUE_COMMITTED_HOP=3
uint8 NO_SAFE_REFERENCE=4
uint8 planning_outcome
uint8 execution_directive
string reason_code
builtin_interfaces/Time global_map_stamp
builtin_interfaces/Time local_map_stamp
builtin_interfaces/Time state_stamp
uint64 mission_revision
bool has_reference
lunar_planning_msgs/MotionReference reference
lunar_planning_msgs/PlannerDiagnostics diagnostics
---
uint8 VALIDATING_INPUT=0
uint8 BUILDING_SNAPSHOT=1
uint8 SEARCHING=2
uint8 OPTIMIZING=3
uint8 CERTIFYING=4
uint8 phase
float64 elapsed_s
uint64 expanded_states
bool has_best_cost
float64 best_cost
