#!/usr/bin/env python3
"""Generate portable training constraints from one qualified host fingerprint."""

from __future__ import annotations

import argparse
import importlib.metadata
import json
import os
import sys
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path


FINGERPRINT_SCHEMA = "lunar-platform-fingerprint/v1"
TRAINING_PROFILE = "train_amd64_rtx4080_super"
LOCKED_DISTRIBUTIONS = ("numpy", "PyYAML", "torch", "rasterio", "shapely")


class StackLockError(ValueError):
    """The host fingerprint or installed training stack is not lockable."""


def load_qualified_fingerprint(path: str | Path) -> dict[str, object]:
    target = Path(path)
    if not target.is_absolute():
        raise StackLockError("fingerprint path must be absolute")
    if target.is_symlink() or not target.is_file():
        raise StackLockError("fingerprint must be an existing regular file")
    try:
        document = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise StackLockError("fingerprint is not valid UTF-8 JSON") from error
    if not isinstance(document, dict):
        raise StackLockError("fingerprint document must be a mapping")
    expected = {
        "schema_version": FINGERPRINT_SCHEMA,
        "profile": TRAINING_PROFILE,
        "os.name": "Ubuntu",
        "os.version_id": "22.04",
        "architecture": "amd64",
        "ros.distro": "humble",
        "gpu.available": True,
        "gpu.model": "NVIDIA GeForce RTX 4080 SUPER",
        "cuda.available": True,
        "readiness.ready": True,
    }
    actual = {
        "schema_version": document.get("schema_version"),
        "profile": document.get("profile"),
        "os.name": _nested(document, "os", "name"),
        "os.version_id": _nested(document, "os", "version_id"),
        "architecture": document.get("architecture"),
        "ros.distro": _nested(document, "ros", "distro"),
        "gpu.available": _nested(document, "gpu", "available"),
        "gpu.model": _nested(document, "gpu", "model"),
        "cuda.available": _nested(document, "cuda", "available"),
        "readiness.ready": _nested(document, "readiness", "ready"),
    }
    mismatches = [
        f"{name}: expected {value!r}, got {actual[name]!r}"
        for name, value in expected.items()
        if actual[name] != value
    ]
    if mismatches:
        raise StackLockError(
            "fingerprint is not ready for the training stack: "
            + "; ".join(mismatches)
        )
    return document


def render_constraints(fingerprint: Mapping[str, object]) -> str:
    if not isinstance(fingerprint, Mapping):
        raise StackLockError("fingerprint must be a mapping")
    cuda_release = _nested(fingerprint, "cuda", "release")
    if not isinstance(cuda_release, str) or not cuda_release:
        raise StackLockError("fingerprint CUDA release is missing")
    versions: list[tuple[str, str]] = []
    for distribution in LOCKED_DISTRIBUTIONS:
        try:
            version = importlib.metadata.version(distribution)
        except importlib.metadata.PackageNotFoundError as error:
            raise StackLockError(
                f"training distribution is not installed: {distribution}"
            ) from error
        if distribution == "torch":
            try:
                import torch
            except ImportError as error:
                raise StackLockError("Torch runtime cannot be imported") from error
            version = torch.__version__
        if not version or any(character.isspace() for character in version):
            raise StackLockError(
                f"training distribution version is invalid: {distribution}"
            )
        versions.append((distribution, version))
    lines = [
        "# Generated by training/tools/lock_training_stack.py",
        "# Platform: Ubuntu 22.04 amd64, ROS 2 Humble, RTX 4080 SUPER",
        f"# CUDA toolkit: {cuda_release}",
    ]
    lines.extend(f"{name}=={version}" for name, version in versions)
    return "\n".join(lines) + "\n"


def write_constraints_atomic(path: str | Path, contents: str) -> None:
    target = Path(path)
    if target.is_symlink():
        raise StackLockError("constraints output must not be a symbolic link")
    if not target.parent.is_dir():
        raise StackLockError("constraints output parent directory is missing")
    descriptor, temporary_name = tempfile.mkstemp(
        dir=target.parent, prefix=f".{target.name}.", suffix=".tmp"
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(contents)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, target)
        directory_fd = os.open(target.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    except Exception as error:
        if temporary.exists():
            temporary.unlink()
        if isinstance(error, StackLockError):
            raise
        raise StackLockError("constraints output could not be written") from error


def _nested(document: Mapping[str, object], *path: str) -> object:
    value: object = document
    for name in path:
        if not isinstance(value, Mapping):
            return None
        value = value.get(name)
    return value


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fingerprint", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    try:
        fingerprint = load_qualified_fingerprint(arguments.fingerprint)
        contents = render_constraints(fingerprint)
        write_constraints_atomic(arguments.output, contents)
    except StackLockError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "StackLockError",
    "load_qualified_fingerprint",
    "main",
    "render_constraints",
    "write_constraints_atomic",
]
